export const ADDED = "todo/added"
export const LOADED = "todo/loaded"
export const TOGGLED = "todo/toggled"
export const COLORSELECTED = "todo/colorselected"
export const DELETED = "todo/deleted"
export const ALLCOMPLETED = "todo/allCompleted"
export const CLEARCOMPLETED = "todo/clearCompleted"